# Copyright (c) 2023 Sapphire's Suite. All Rights Reserved.

name: Options


# Trigger the action.
on:
  push:
    branches:
      - main
      - master
      - dev
      - dev_*
      - '!dev_osx'
      - '!dev_macos'
      - '!dev_win'
      - '!dev_windows'



# Settings common to all jobs.
defaults:
  run:
    shell: bash



# Variables common to all jobs.
env:
  CMAKE_V: '3.17.0'
  CMAKE_OPTIONS: '-DSA_CI=1'



# Job matrix
jobs:

  Options:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
        option:
          - ""


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master # Install Ninja.

      - name: "[Package] Install LLVM and Clang"
        run: sudo apt-get install clang

      - name: Generate Project
        run: cmake --preset="Clang" ${{ matrix.option }} ${{ env.CMAKE_OPTIONS }}

      - name: Build Project
        run: cmake --build --preset="Clang ${{ matrix.config }}" --verbose

      - name: Run CTests
        run: ctest --preset="Clang ${{ matrix.config }}" -V
